DOCKERFILE: "../Dockerfile"
TAG: "iamlab-cmu/azure_kinect:humble"
ARGS:
  BASE_IMAGE: "iamlab-cmu/ros_cuda:humble"
  ROS_DISTRO: "humble"
  ROS_VERSION: 2
  INSTALL_ROS: False
  POST_INSTALL:
    - "apt-get update && apt-get upgrade -y"
    - "apt-get install -y curl openssh-server git vim terminator software-properties-common"
    - "apt-get install -y autoconf automake libtool curl make g++ unzip"
    - "apt-get install -y python3-distutils"
    - "pip3 install rosdep empy"
    - "source /opt/ros/${ROS_DISTRO}/setup.bash"
    - "echo source /opt/ros/${ROS_DISTRO}/setup.bash >> ${HOME}/.bashrc"
    - "cp /etc/apt/sources.list /etc/apt/sources.list.bkp"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal universe' >> /etc/apt/sources.list"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal-updates universe' >> /etc/apt/sources.list"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal main restricted' >> /etc/apt/sources.list"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal-updates main restricted' >> /etc/apt/sources.list"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal multiverse' >> /etc/apt/sources.list"
    - "echo 'deb http://archive.ubuntu.com/ubuntu focal-updates multiverse' >> /etc/apt/sources.list"
    - "apt-get update && apt-get install -y libsoundio1"
    - "rm /etc/apt/sources.list && mv /etc/apt/sources.list.bkp /etc/apt/sources.list"
    - "apt autoremove && apt clean -y && rm -rf /var/lib/apt/lists/*"
    - "apt-get update"
    - "wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/libk4a1.4-dev/libk4a1.4-dev_1.4.1_amd64.deb"
    - "wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/libk4a1.4/libk4a1.4_1.4.1_amd64.deb"
    - "wget https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/k/k4a-tools/k4a-tools_1.4.1_amd64.deb"
    - "ACCEPT_EULA=y dpkg -i libk4a1.4* k4a-tools*"
    - "rm libk4a1.4*"
    - "rm k4a-tools*"
    - "mkdir -p ${HOME}/ros/${ROS_DISTRO}/src && cd ${HOME}/ros/${ROS_DISTRO}/src"
    - "git clone https://github.com/kevin-zhang-sony/Azure_Kinect_ROS_Driver -b ${ROS_DISTRO}-devel"
    - "pip3 install xacro"
    - "apt-get install -y ros-${ROS_DISTRO}-joint-state-publisher libangles-dev"
    - "cd .."
    - "colcon build"
    - "source ${HOME}/ros/${ROS_DISTRO}/install/setup.bash"
    - "echo source ${HOME}/ros/${ROS_DISTRO}/install/setup.bash >> ${HOME}/.bashrc"
NOCACHE: FALSE

