DOCKERFILE: "../Dockerfile"
TAG: "iamlab-cmu/franka_interface:noetic"
ARGS:
  BASE_IMAGE: "ros:noetic"
  ROS_DISTRO: "noetic"
  ROS_VERSION: 1
  INSTALL_ROS: False
  POST_INSTALL:
    - "apt-get update && apt-get upgrade -y"
    - "apt-get install -y curl openssh-server git vim terminator"
    - "apt-get install -y autoconf automake libtool make g++ unzip"
    - "apt-get install -y ros-${ROS_DISTRO}-desktop"
    - "mkdir -p ${HOME}/Documents && cd ${HOME}/Documents"
    - "wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.zip"
    - "unzip protobuf-all-21.12.zip"
    - "cd protobuf-21.12"
    - "./configure"
    - "make -j`nproc`"
    - "make install"
    - "ldconfig"
    - "cd .."
    - "apt-get install -y python3-distutils"
    - "wget https://bootstrap.pypa.io/get-pip.py"
    - "python3 get-pip.py"
    - "rm get-pip.py"
    - "pip3 install rosdep catkin-tools empy"
    - "git clone --recurse-submodules https://github.com/iamlab-cmu/franka-interface.git"
    - "cd franka-interface" 
    - "bash ./bash_scripts/clone_libfranka.sh 3"
    - "bash ./bash_scripts/make_libfranka.sh"
    - "bash ./bash_scripts/make_franka_interface.sh"
    - "apt-get install -y ros-${ROS_DISTRO}-libfranka ros-${ROS_DISTRO}-franka-ros"
    - "rm -rf /etc/ros/rosdep/sources.list.d/20-default.list"
    - "rosdep init && rosdep update && rosdep install -ryi --from-paths ./"
    - "source /opt/ros/${ROS_DISTRO}/setup.bash"
    - "echo source /opt/ros/${ROS_DISTRO}/setup.bash >> ${HOME}/.bashrc"
    - "bash ./bash_scripts/make_catkin.sh"
    - "source ${HOME}/Documents/franka-interface/catkin_ws/devel/setup.bash --extend"
    - "echo source ${HOME}/Documents/franka-interface/catkin_ws/devel/setup.bash --extend >> ${HOME}/.bashrc"
NOCACHE: False
