DOCKERFILE: "../Dockerfile"
TAG: "iamlab-cmu/frankapy:noetic"
ARGS:
  BASE_IMAGE: "iamlab-cmu/ros_cuda:noetic"
  ROS_DISTRO: "noetic"
  ROS_VERSION: 1
  INSTALL_ROS: False
  POST_INSTALL:
    - "apt-get update && apt-get upgrade -y" 
    - "apt-get install -y openssh-server git vim terminator"
    - "apt-get install -y autoconf automake libtool lsb-release curl make g++ unzip"
    - "apt-get install -y python3-distutils python3-tk"
    - "wget https://bootstrap.pypa.io/get-pip.py"
    - "python3 get-pip.py"
    - "rm get-pip.py"
    - "pip3 install rosdep catkin-tools empy"
    - "mkdir -p ${HOME}/Documents && cd ${HOME}/Documents"
    - "wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.zip"
    - "unzip protobuf-all-21.12.zip"
    - "cd protobuf-21.12"
    - "./configure"
    - "make -j`nproc`"
    - "make install"
    - "ldconfig"
    - "cd .."
    - "git clone --recurse-submodules https://github.com/iamlab-cmu/frankapy.git"
    - "cd frankapy"
    - "source /opt/ros/${ROS_DISTRO}/setup.bash"
    - "echo source /opt/ros/${ROS_DISTRO}/setup.bash >> ${HOME}/.bashrc"
    - "pip3 install -e ."
    - "pip3 install --upgrade protobuf"
    - "./bash_scripts/make_catkin.sh"
    - "apt-get install -y ros-${ROS_DISTRO}-libfranka ros-${ROS_DISTRO}-franka-ros"
    - "source ${HOME}/Documents/frankapy/catkin_ws/devel/setup.bash --extend"
    - "echo source ${HOME}/Documents/frankapy/catkin_ws/devel/setup.bash --extend >> ${HOME}/.bashrc"
NOCACHE: False