DOCKERFILE: "../Dockerfile"
TAG: "iamlab-cmu/frankapy:humble"
ARGS:
  BASE_IMAGE: "iamlab-cmu/ros_cuda:humble"
  ROS_DISTRO: "humble"
  ROS_VERSION: 2
  INSTALL_ROS: False
  POST_INSTALL:
    - "apt-get update && apt-get upgrade -y" 
    - "apt-get install -y openssh-server git vim terminator"
    - "apt-get install -y autoconf automake libtool lsb-release curl make g++ unzip"
    - "apt-get install -y python3-distutils python3-tk"
    - "pip3 install rosdep empy"
    - "source /opt/ros/${ROS_DISTRO}/setup.bash"
    - "echo source /opt/ros/${ROS_DISTRO}/setup.bash >> ${HOME}/.bashrc"
    - "mkdir -p ${HOME}/Documents && cd ${HOME}/Documents"
    - "wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.zip"
    - "unzip protobuf-all-21.12.zip"
    - "cd protobuf-21.12"
    - "./configure"
    - "make -j`nproc`"
    - "make install"
    - "ldconfig"
    - "pip3 install protobuf==4.21.10"
    - "cd .."
    - "apt install -y libpoco-dev libeigen3-dev"
    - "git clone https://github.com/frankaemika/libfranka.git"
    - "cd libfranka"
    - "git checkout 80197c6"
    - "git submodule update --init --recursive"
    - "mkdir build && cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF .."
    - "cmake --build . -j$(nproc)"
    - "cpack -G DEB"
    - "dpkg -i libfranka-*.deb"
    - "cd ../.."
    - "git clone https://github.com/iamlab-cmu/frankapy.git"
    - "cd frankapy"
    - "git checkout ros2_humble"
    - "git submodule update --init --recursive"
    - "pip3 install -e ."
    - "./bash_scripts/make_ros2_ws.sh"
    - "source ${HOME}/Documents/frankapy/ros2_ws/install/setup.bash"
    - "echo source ${HOME}/Documents/frankapy/ros2_ws/install/setup.bash >> ${HOME}/.bashrc"
NOCACHE: False
