DOCKERFILE: "../Dockerfile"
TAG: "iamlab-cmu/franka_interface:humble"
ARGS:
  BASE_IMAGE: "ros:humble"
  ROS_DISTRO: "humble"
  ROS_VERSION: 2
  INSTALL_ROS: False
  POST_INSTALL:
    - "apt-get update && apt-get upgrade -y"
    - "apt-get install -y software-properties-common"
    - "add-apt-repository universe"
    - "apt-get install -y curl wget git vim terminator"
    - "apt-get install -y autoconf automake libtool make g++ unzip"
    - "apt-get install -y ros-${ROS_DISTRO}-desktop"
    - "rosdep update"
    - "source /opt/ros/${ROS_DISTRO}/setup.bash"
    - "echo source /opt/ros/${ROS_DISTRO}/setup.bash >> ${HOME}/.bashrc"
    - "apt-get install -y ros-${ROS_DISTRO}-control-msgs ros-${ROS_DISTRO}-xacro ros-${ROS_DISTRO}-angles ros-${ROS_DISTRO}-ros2-control"
    - "apt-get install -y ros-${ROS_DISTRO}-realtime-tools ros-${ROS_DISTRO}-control-toolbox ros-${ROS_DISTRO}-moveit ros-${ROS_DISTRO}-ros2-controllers"
    - "apt-get install -y ros-${ROS_DISTRO}-joint-state-publisher ros-${ROS_DISTRO}-joint-state-publisher-gui ros-${ROS_DISTRO}-ament-cmake-clang-format"
    - "apt-get install -y ros-${ROS_DISTRO}-robot-state-publisher ros-${ROS_DISTRO}-action-tutorials-interfaces"
    - "mkdir -p ${HOME}/Documents && cd ${HOME}/Documents"
    - "wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.zip"
    - "unzip protobuf-all-21.12.zip"
    - "cd protobuf-21.12"
    - "./configure"
    - "make -j`nproc`"
    - "make install"
    - "ldconfig"
    - "cd .."
    - "apt install -y libpoco-dev libeigen3-dev"
    - "git clone https://github.com/SNAAK-CMU/libfranka.git"
    - "git checkout stable"
    - "git submodule update --init --recursive"
    - "mkdir build && cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF .."
    - "cmake --build . -j$(nproc)"
    - "cpack -G DEB"
    - "dpkg -i libfranka-*.deb"
    - "cd ../.."
    - "git clone https://github.com/iamlab-cmu/franka-interface.git"
    - "cd franka-interface" 
    - "git checkout ros2_humble"
    - "git submodule update --init --recursive"
    - "mv ~/Documents/libfranka ."
    - "bash ./bash_scripts/make_libfranka.sh"
    - "bash ./bash_scripts/make_franka_interface.sh"
    - "bash ./bash_scripts/make_ros2_ws.sh"
    - "mv build/franka-interface/proto/libproto.so /usr/local/lib/"
    - "mv build/franka-interface-common/libfranka-interface-common.so /usr/local/lib/"
    - "ldconfig"
    - "source ${HOME}/Documents/franka-interface/ros2_ws/install/setup.bash"
    - "echo source ${HOME}/Documents/franka-interface/ros2_ws/install/setup.bash >> ${HOME}/.bashrc"
NOCACHE: False

