version: "3"

services:
  franka-interface:
    image: "iamlab-cmu/franka_interface:noetic"
    container_name: "franka_interface_noetic"
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "ROBOT_IP=${ROBOT_IP}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "cd /root/Documents/franka-interface/build && ./franka_interface --robot_ip ${ROBOT_IP} --with_gripper 0"

  franka-ros-interface:
    image: "iamlab-cmu/franka_interface:noetic"
    container_name: "franka_ros_interface_noetic"
    depends_on:
      - franka-interface
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "ROBOT_IP=${ROBOT_IP}"
      - "ROBOT_NUM=${ROBOT_NUM}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
    privileged: true
    network_mode: "host"
    ipc: "host"
    restart: "unless-stopped"
    command: bash -c "cd /root/Documents/franka-interface && source catkin_ws/devel/setup.bash --extend && sleep 5 && roslaunch franka_ros_interface franka_ros_interface.launch robot_num:=${ROBOT_NUM}"

  franka-gripper:
    image: "iamlab-cmu/franka_interface:noetic"
    container_name: "franka_gripper_noetic"
    depends_on:
      - franka-interface
      - franka-ros-interface
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
      - "ROS_IP=${ROS_IP}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
      - "ROBOT_IP=${ROBOT_IP}"
      - "ROBOT_NUM=${ROBOT_NUM}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
    privileged: true
    network_mode: "host"
    restart: "unless-stopped"
    command: bash -c "cd /root/Documents/franka-interface && source catkin_ws/devel/setup.bash --extend && roslaunch franka_ros_interface franka_gripper.launch robot_num:=${ROBOT_NUM} robot_ip:=${ROBOT_IP}"
