version: "3"

services:
  azure_kinect_noetic:
    image: iamlab-cmu/azure_kinect:noetic
    container_name: azure_kinect_noetic
    environment:
      - "DISPLAY=unix${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      - "LIBGL_ALWAYS_SOFTWARE=1"
      - "LIBGL_ALWAYS_INDIRECT="
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    restart: "unless-stopped"
    command: roslaunch azure_kinect_ros_driver driver.launch fps:=30 depth_mode:=NFOV_UNBINNED sensor_sn:=_${SENSOR_SN}
